# Generated by Django 2.0.2 on 2018-03-04 18:53

from django.db import migrations, models
import django.db.models.deletion
import planogram.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('vendor_code', models.CharField(default=planogram.models.default_vendor_code, max_length=20, verbose_name='Артикул')),
                ('image', models.ImageField(default='catalog/default.png', upload_to='catalog/', verbose_name='Изображение')),
                ('width', models.PositiveIntegerField(default=10, help_text='Указывать в см', verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=10, help_text='Указывать в см', verbose_name='Высота')),
                ('length', models.PositiveIntegerField(default=10, help_text='Указывать в см', verbose_name='Длина')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planogram.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['title'],
            },
        ),
    ]
