# Generated by Django 2.0.3 on 2018-05-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planogram', '0003_auto_20180304_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя планограммы')),
                ('file', models.TextField(verbose_name='Планограмма')),
            ],
            options={
                'verbose_name_plural': 'Планограммы',
                'verbose_name': 'Планограмма',
                'ordering': ['title'],
            },
        ),
    ]
