# Generated by Django 2.0.3 on 2018-05-30 15:18

from django.db import migrations, models
import django.db.models.deletion
import planogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('planogram', '0004_planogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='planogram.Category', verbose_name='Родительский каталог'),
        ),
        migrations.AddField(
            model_name='category',
            name='ref',
            field=models.CharField(default=planogram.models.default_vendor_code, max_length=200, verbose_name='Уникальный код'),
        ),
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default=planogram.models.default_vendor_code, max_length=200, verbose_name='Уникальный код'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planogram.Category', verbose_name='Категория'),
        ),
    ]
