# Generated by Django 2.0.3 on 2018-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planogram', '0005_auto_20180530_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planogram',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя планограммы'),
        ),
    ]
