# Generated by Django 2.0.3 on 2018-06-28 13:18

from django.db import migrations, models
import planogram.models


class Migration(migrations.Migration):

    dependencies = [
        ('planogram', '0006_auto_20180615_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default=planogram.models.default_vendor_code, max_length=200, verbose_name='Артикул'),
        ),
    ]
